version: '3.3'

services:
  # Frontend HTML
  frontend:
    container_name: "tutorfrontend"
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - 9030:80
    deploy:
      restart_policy:
        condition: on-failure
    image: jiameelorh/eti-tutorfrontend
    networks:
      - s10192803networkbridge

  # Tutor Microservice
  tutorcontainerS10192803:
    build:
      context: ./Tutor
      dockerfile: Dockerfile
    container_name: tutorcontainerS10192803
    ports:
      - 9031:9031
    image: jiameelorh/eti-tutorcontainer
    networks:
      - s10192803networkbridge

  # Testing Microservice
  testingcontainer:
    build:
      context: ./Testing
      dockerfile: Dockerfile
    container_name: testingcontainer
    ports:
      - 9032:9032
    image: jiameelorh/eti-testcontainer
    networks:
      - s10192803networkbridge

networks:
  s10192803networkbridge:
    driver: bridge