name: CI to push to docker

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: docker build TutorContainer
      run: |
        docker build ./Tutor -t jiameelorh/eti-tutorcontainer
    - name: docker build Testing
      run: |
        docker build ./Testing -t jiameelorh/eti-testcontainer
    - name: docker build Front-end
      run: |
        docker build ./Front-end -t jiameelorh/eti-tutorfrontend
    - name: docker push
      run: |
        docker push jiameelorh/eti-tutorcontainer
        docker push jiameelorh/eti-testcontainer
        docker push jiameelorh/eti-tutorfrontend